### ISSUE TITLE
Missing documentation in for some functions

### ISSUE THREAD

**Issue by disclaimedication** [rshcs/Grow-R503-Finger-Print#8]
README does not include documentation for auto_enroll() and auto_identify(). Please suggest the configuration procedure for these functions. @rshcs

**Comment by rshcs** [comment]
> README does not include documentation for auto_enroll() and auto_identify(). Please suggest the configuration procedure for these functions. @rshcs

This is noted.

**Comment by rshcs** [comment]
- You can use the following documentation until the readme is updated.
[grow-r503-docs.readthedocs.io](https://grow-r503-docs.readthedocs.io/en/latest/r503.html)
