### ISSUE TITLE
RFI - Is it possible to directly connect to UART pins

### ISSUE THREAD

**Issue by hidara2000** [rshcs/Grow-R503-Finger-Print#9]
Hi,
I am about to purchase one of these sensors and wish to connect directly to UART pins without using the USB-TTL adapter. Is this possible? . Cheers

**Comment by rshcs** [comment]
> Hi, I am about to purchase one of these sensors and wish to connect directly to UART pins without using the USB-TTL adapter. Is this possible? . Cheers

Hi,

If you plan to use it with Raspberry Pi UART pins, then the answer is yes. 
If you use it with a Windows PC then you need some sort of USB to Serial converter.
In general, you have to make sure that the fingerprint sensor and the upper computer use the same logic level voltage and the same communication protocol.

If you plan to use it with a microcontroller then you can use the code in the following repo (Note: only tested with esp32). I have not added the documentation yet but the functionality is almost the same.
https://github.com/rshcs/r503_uPython

Feel free to ask if you need further clarification.

Cheers.
